/*
 * File: app/store/RestaurantStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.RestaurantStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Restaurant'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Restaurant',
        storeId: 'Restaurants',
        proxy: {
            type: 'jsonp',
            url: 'https://api.foursquare.com/v2/venues/search',
            reader: {
                type: 'json',
                rootProperty: 'response.venues'
            }
        },
        grouper: {
            groupFn: function(record) {
                var distM = record.raw.location.distance;
                var distMiles = Math.round(distM * 0.000621371); //give or take.
                return (distMiles == 1)?"1 Mile":distMiles+' Miles';
            }
        },
        sorters: [
            { property: 'name', direction: 'ASC' }
        ]
    }
});