/*
 * File: app/view/confirmLocation.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.confirmLocation', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                height: 40,
                html: 'Please confirm your location:'
            },
            {
                xtype: 'map',
                height: 200,
                minHeight: 375,
                flex: 1
            },
            {
                xtype: 'segmentedbutton',
                height: 40,
                margin: '10 0 10 0',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'button',
                        text: 'Next'
                    }
                ]
            }
        ]
    }

});