/*
 * File: app/view/mainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mainView', {
    extend: 'Ext.navigation.View',

    config: {
        navigationBar: {
            items: [
                {
                    xtype: 'button',
                    id: 'addContactButton',
                    ui: 'action',
                    iconCls: 'add',
                    iconMask: true,
                    align: 'right'
                }
            ]
        },
        items: [
            {
                xtype: 'container',
                id: 'homeScreen',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        margin: 75,
                        text: 'Get Started!',
                        flex: 1
                    }
                ]
            }
        ]
    }

});