/*
 * File: app/view/restaurantList.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.restaurantDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.restaurantdetails',
    title: 'Details',
    config: {
        tpl: [
            '<div class="restaurant"><span class="name">{name}</span>',
            '<tpl for="contact">',
            '<span class="phone">- {formattedPhone}</span>',
            '</tpl>',
            '<div class="icons"><tpl for="categories">',
            '<span><img src="{icon.prefix}32{icon.suffix}" /></span>',
            '</tpl></div>',
            '<div class="address">Address:<br />',
            '<tpl for="location">',
            '{address}<br />',
            '{city}, {state} {postalCode}',
            '</tpl></div>',
            '<tpl for="menu">',
            '<a class="menu" href="{mobileUrl}">Menu</a>',
            '</tpl>',
            '<tpl for="specials">',
            '<tpl if="count &gt; 0">',
            '<div class="specials">Specials:<dl><tpl for="items">',
            '<dt>{title}</dt>',
            '<dd>{description}<br>{message}</dd>',
            '</tpl></dl></div>',
            '</tpl>',
            '</tpl>',
            '</div>'
        ]
    }

});