/*
 * File: app/view/ViewPortContainer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ViewPortContainer', {
    extend: 'Ext.Container',

    config: {
        id: 'viewport',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'navigationview',
                id: 'mainView',
                navigationBar: {
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                Ext.getCmp('viewport').setActiveItem(1);
                            },
                            id: 'addContactButton',
                            ui: 'action',
                            iconCls: 'add',
                            iconMask: true,
                            align: 'right'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'container',
                        id: 'homeScreen',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                margin: 75,
                                text: 'Get Started!',
                                flex: 1
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'editContact',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'textfield',
                        label: 'First Name',
                        labelWidth: '40%',
                        name: 'firstname'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Last Name',
                        labelWidth: '40%',
                        name: 'lastname'
                    },
                    {
                        xtype: 'label',
                        html: 'Choose what kind of food they like:'
                    },
                    {
                        xtype: 'list',
                        id: 'categoryList',
                        itemTpl: [
                            '<div><span class="icon"><img src="{imgURL}" /></span> {shortName}</div>'
                        ],
                        store: 'MyJsonStore',
                        mode: 'MULTI',
                        flex: 1
                    },
                    {
                        xtype: 'segmentedbutton',
                        margin: '0 0 10 0',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: 'Cancel'
                            },
                            {
                                xtype: 'button',
                                text: 'Save'
                            }
                        ]
                    },
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: 'Add Contact'
                    }
                ]
            }
        ]
    }

});